<?php

namespace App\Tests\Security;
use App\Service\BillingClient;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class AuthControlTest extends WebTestCase
{
    private BillingClient $billingClient;
    private KernelBrowser $client;
    protected function setUp(): void
    {
        parent::setUp();
        $this->client = static::createClient();
        $this->client->disableReboot();
    }

    protected function tearDown(): void
    {
        $this->client->enableReboot();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testRegisterSuccess(): void
    {
        $crawler = $this->client->request('GET', '/register');
        self::assertResponseIsSuccessful();

        $form = $crawler->selectButton('Зарегестрироваться')->form();
        $form->setValues([
            'registration[email]' => 'new@email.test',
            'registration[password][first]' => 'password',
            'registration[password][second]' => 'password',
        ]);
        $this->client->submit($form);
        self::assertResponseRedirects();

        // Проверяем что авторизация в нового пользователя прошла успешно
        $this->client->followRedirect();
        $token = static::getContainer()
            ->get('security.untracked_token_storage')
            ->getToken();
        self::assertNotNull($token, 'Token отсутствует');
        self::assertSame("new@email.test", $token->getUser()->getEmail());
    }

    public function testAuthSuccess(): void {
        $crawler = $this->client->request('GET', '/login');
        self::assertResponseIsSuccessful();

        $form = $crawler->selectButton('Войти')->form();
        $form->setValues([
            'email' => 'user@test.local',
            'password' => 'user_password',
        ]);
        $this->client->submit($form);
        self::assertResponseRedirects();

        // Проверка успешной авторизации
        $this->client->followRedirect();
        $token = static::getContainer()
            ->get('security.untracked_token_storage')
            ->getToken();
        self::assertNotNull($token, 'Token отсутствует');
        self::assertSame("user@test.local", $token->getUser()->getEmail());
    }
}
