name: CI
on:
    push:
        branches: [ "master" ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        environment: deploy_env
        #   ubuntu-latest должна работать стабильно, можно указать явно другую версию
        #   steps можно сильнее разбить на категории
        #   тут представлен пример только для запуска тестов. Можно еще проверять код-стайл и доступность документации
        #   часто встречается на рабочих проектах
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4.5'
                    extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
                    coverage: pcov
                    tools: composer
            -   name: Setting environment and composer
                # скорректируйте название БД и контейнера, если нужно
                run: |
                    echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
                    echo "TRUSTED_HOSTS=${{ secrets.APP_TRUSTED_HOSTS }}" >> .env.local
                    echo "POSTGRES_DB=${{ secrets.APP_POSTGRES_DB }}" >> .env.local
                    echo "POSTGRES_USER=${{ secrets.APP_POSTGRES_USER }}" >> .env.local
                    echo "POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }}" >> .env.local
                    echo "DATABASE_URL=pgsql://${{ secrets.APP_POSTGRES_USER }}:${{ secrets.APP_POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.APP_POSTGRES_DB }}" >> .env.local
                    composer install

            -   name: Setting Docker
                run: |
                    sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
                    docker-compose --version
                    mkdir ~/.yarn
                    # нужно создать сеть, так как в github Actions study-on изолирован от биллинга
                    docker network create study-onbilling_default
                    docker compose build
                    docker compose up -d
                    docker compose run -u root --entrypoint sh node -lc "corepack enable && yarn install"
                    docker compose run -u root --entrypoint sh node -lc "corepack enable && yarn encore dev"
                    docker ps -a
            -   name: Setting test environment and DB
                # скорректируйте название БД и контейнера, если нужно
                run: |
                    echo "DATABASE_URL=pgsql://${{ secrets.DB_TEST_USER }}:${{ secrets.DB_TEST_PASSWORD }}@postgres:5432/${{secrets.DB_TEST_DBNAME}}" >> .env.test.local
                    ls -la
                    docker ps -a
                    docker compose exec -T php bin/console doctrine:database:drop --force --env=test || true
                    docker compose exec -T php bin/console doctrine:database:create --env=test
                    docker compose exec -T php bin/console doctrine:migrations:migrate -n --env=test
                    docker compose exec -T php bin/console doctrine:fixtures:load -n --env=test
            -   name: run PHPUnit
                run: |
                    docker compose exec -T php sh -c 'APP_ENV=test bin/phpunit'
